home_page:
    pattern:  /
    defaults: { _page: "Mni\\PagesDemoBundle\\Page\\HomePage" }

random_number_component:
    pattern:  /randomnumber
    defaults: { _component: "Mni\\PagesDemoBundle\\Component\\RandomNumberComponent" }
