parameters:

services:
    mnapoli.twig.pages_extension:
        class: Mni\PagesBundle\Twig\PagesExtension
        arguments:
            - "@fragment.handler"
            - "@router"
        tags:
            - { name: twig.extension }
