parameters:
#    mni_pages.example.class: Mni\PagesBundle\Example

services:
#    mni_pages.example:
#        class: %mni_pages.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
