# MniPagesDemoBundle routes
mni_pagesdemo:
    resource: "@MniPagesDemoBundle/Resources/config/routing.yml"

# MniPagesBundle routes
mni_pages:
    resource: "@MniPagesBundle/Resources/config/routing.yml"
    prefix:   /mnipages
